# This file created by conda-build 3.21.8
# ------------------------------------------------

package:
  name: starlette
  version: 0.19.1
source:
  sha256: c6d21096774ecb9639acad41b86b7706e52ba3bf1dc13ea4ed9ad593d47e24c7
  url: https://pypi.io/packages/source/s/starlette/starlette-0.19.1.tar.gz
build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --no-build-isolation -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2021.10.8 ha878542_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 11.2.0 h1d223b6_15
    - libgomp 11.2.0 h1d223b6_15
    - libnsl 2.0.0 h7f98852_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.11 h166bdaf_1014
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.2 h166bdaf_1
    - pip 22.0.4 pyhd8ed1ab_0
    - python 3.10.4 h2660328_0_cpython
    - python_abi 3.10 2_cp310
    - readline 8.1 h46c0cb4_0
    - setuptools 62.1.0 py310hff52083_0
    - sqlite 3.38.2 h4ff8645_0
    - tk 8.6.12 h27826a3_0
    - tzdata 2022a h191b570_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h166bdaf_1014
  run:
    - anyio >=3.4.0,<5.0.0a
    - python >=3.7
    - typing_extensions
test:
  commands:
    - python -c "from starlette import *"
about:
  description: 'Starlette is a lightweight [ASGI](https://asgi.readthedocs.io/en/latest/)

    framework/toolkit.


    It is ideal for building high performance asyncio services, and supports

    both HTTP and WebSockets.

    '
  dev_url: https://github.com/encode/starlette/
  doc_url: https://www.starlette.io/
  home: https://www.starlette.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: "The little ASGI framework that shines. \u2728"
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - carlodri
    - dgasmith
